# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 03:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Utilidad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilidad',
            name='utilidad',
        ),
        migrations.DeleteModel(
            name='Tipo_Utilidad',
        ),
    ]
