# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cliente', '0001_initial'),
        ('Trabajador', '__first__'),
        ('Producto', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega_pedido', models.DateTimeField()),
                ('cantidad', models.IntegerField(default='1')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.Cliente')),
                ('estado_pedido', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Pedido.Estado_Pedido')),
                ('producto', models.ManyToManyField(to='Producto.Producto')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trabajador.Trabajador')),
            ],
        ),
    ]
